theme: jekyll-theme-minimal

encoding: 'utf-8'
# Configure the plugin here
category_path: "category" # <- default value
category_layout: "category.html" # <- default value

paginate: 5
paginate_path: "blog/page:num"
